### ISSUE TITLE
[PL] Spring w logice domeny

### ISSUE THREAD

**Issue by splaw88** [coi-gov-pl/spring-clean-architecture#2]
Hejka,

@cardil 
zainteresowalem sie tym ciekawym projektem ale mam jedna uwage pod dyskusje. Mianowicie zgodnie z prezentacja "Wujka Bob'a" i ogolnie z podejsciem czystej architektury tej jak i innych podobnych/powiazanych/pokrewnych framework opdowiedzialny za Dependency Injection powinien byc tez odseparowany od domeny/logiki aplikacji i traktowany jako wymienny plugin. 

Dlatego wszelkie adnotacje Component, Service (w ogole zaleznosc od springframework) powinny zniknac np. na rzecz interfejsow fabryk ktore by te komponenty wstrzykiwaly w uzycia Inject. implementacja tych fabryk powinna byc w zewnetrznym komponencie tak jak masz osobno prezentacje i persistent-stub albo nawet skoro Application jest zarzadzany springiem to moze wrecz tam. 

Jak uwazasz?

**Comment by cardil** [comment]
Specjalnie zrobiłem to w taki sposób. Wydzielanie DI do osobnego komponentu wydaje mi się lekką przesadą. Dzięki temu że używam bezpośrednio `@Component` czy `@Service` mogę tak oznaczać również klasy nie publiczne. Przy konfiguracji zewnętrznej, klasy implementacji muszą być publiczne.

Ale oczywiście można tak zrobić. Np. tutaj jest to pokazane: https://github.com/mattia-battiston/clean-architecture-example Dzięki temu można ten sam kod domeny wykorzystać w zupełnie innej aplikacji np. w Androidzie via dagger albo winnej aplikacji webowej via Guice. Choć osobiście wydaje mi się to naciągane.

Także celowo i świadomie napisałem to w taki sposób, chcąc zmniejszyć ilość części ruchomych.

**Comment by mchalapuk** [comment]
@cardil, mam wrażenie, że @splaw88 ma na myśli odseparowanie frameworka (każdego) od kodu domenowego. Chodzi o tylko o adnotacje. DI zostaje. DI to design konstruktorów.

Napiszę, jakie są moje przemyślenia na ten temat.

Jeśli chodzi o tzw "sensowność" czy "życiowość" tego wydzielania, to myślę, że niedługo (tzn tyle, ile to jest niedługo w świecie Javy 😉) będzie to wymagane, bo aplikacje izomorficzne będą standardem.

Dla mnie jednak sensowność nie jest najważniejsza. Nie jestem taki mądry, żeby wyobrazić sobie wszystkie konteksty wykorzystania kodu domenowego, które będą potrzebne w przyszłości. Bardziej kierowałbym się tutaj zasadami czystego kodu i wyrabianiem dobrych nawyków.

Mam też wrażenie, że od jakiegoś czasu wszyscy zakładają, że warstwa domenowa powinna być przenośna. Ten koncept był już popularny w poprzedniej dekadzie. Pisał o tym nie tylko Wujek Bob, ale i Martin Fowler, Eric Evans, i pewnie wielu innych. Ja bym z tym nie walczył.

Kolejna sprawa, że klasa konfiguracji DI, to bardzo dobry, elegancki pattern i, moim zdaniem, jedno z największych osiągnięć Springa. Zachęcam Cię do ponownego rozważenia sprawy. Jeśli ten projekt ma służyć celom edukacyjnym, to, IMO, ten pattern jest czymś, czego warto uczyć.

Pozdrawiam :octocat:

**Comment by cardil** [comment]
Wszystko ma swoje plusy i minusy. Konfiguracja DI poza klasą implementacji najczęściej staje się centralnym miejscem które jest otwarte na modyfikacje co prowadzi do konfliktów. Dodatkowo to kolejne miejsce które trzeba zmieniać. Dla mnie narzut problemów związanych z konfiguracją zewnętrzną jest w większości przypadków zbyt duży.

**Comment by splaw88** [comment]
To fakt narzut jest spory bo jest to kolejna warstwa podatna na zmiany szczegolnie w poczatkowych fazach developmentu ale i pozniejszych. Nie wiem jakie bylo twoje zalozenie podczas pisania tego czy czystko edukacyjne czy na potrzeby systemow w COI. W COI ze wzgledu na specyfike pisanych systemow faktycznie rozwarstwienie DI od Domeny jest zbedne bo stack technologiczny jest znany z grubsza od samego poczatku i zbytnio sie nie zmienia. Ale jestem sobie w stanie wyobrazic sytuacje gdzie firma tworzy produkt ktorym chce wchodzic do firm i np gdyby napisac to w springu a w przetargu ktory chciala by owa firma wygrac byl zapis ze aplikacja ma byc w EJB no to takie rozwarstwienie bylo by istnie blogoslawienstwem :) 

I tak jak pisal @muroc jesli jest to czysto edukacyjne to rozwaz czy nie warto pokazac jak zrobic rozdzielenie Springa od domeny istnie elegancko (chetnie sam to bym zobaczyl :) )

**Comment by cardil** [comment]
Wrzuciłem implementację pokazującą jak zaimplementować konfigurację w separacji od logiki domeny. Dalej uważam że to przesada i tylko niepotrzebna komplikacja, ale zostawię to dla wglądu.

Branch: https://github.com/coi-gov-pl/spring-clean-architecture/tree/feature/external-spring-configuration

Tutaj diff: https://github.com/coi-gov-pl/spring-clean-architecture/compare/feature/external-spring-configuration

**Comment by cardil** [comment]
Zmieniłem rekomendację na zewnętrzną konfigurację. Mieliście racje Panowie!
